server:
  port: 8000
spring:
  application:
    name: api-gateway
  reactor:
    context-propagation: auto
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**,/api/users/**
            - id: wallet-service
              uri: lb://WALLET-SERVICE
              predicates:
                - Path=/api/wallet/**,/internal/position/stream/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/order/**,/api/order-conditions/**
            - id: market-data-service
              uri: lb://MARKET-DATA-SERVICE
              predicates:
                - Path=/api/klines/**,/api/price/**
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
    include-application-name: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: gateway
  tracing:
    sampling:
      probability: 1.0     # dev: 1.0 (100%). Production giảm còn 0.1 (10%)
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://jaeger:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false

  logging:
    export:
      otlp:
        endpoint: http://jaeger:4318/v1/logs

jwt:
  signerKey: ${JWT_SIGNER_KEY}
