spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: cryptoshield
  datasource:
    url: jdbc:postgresql://localhost:5433/crypto_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: ${signerKey}