spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  instance:
    hostname: discovery-service
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF