server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/crypto_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: rykFmaUEc8gl79dPCjSQTQRGfdpR68aehBLWrr1FmOA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/